### ISSUE TITLE
IID and Non-IID Settings??

### ISSUE THREAD

**Issue by Pnme79** [rruisong/pytorch_federated_learning#3]
如对FedAVG + mnist+ 区分NON-IID 和IID了吗？

**Comment by rruisong** [comment]
There are several ways to make the dataset Non-IID. The simplest approach involves modifying the _num_local_class_ parameter in the configuration file.

**Comment by 1496nuonuo** [comment]
When num_local_class is 10, I think it will be IID. If less than 10, like 2, it will be the Non-IID
