### ISSUE TITLE
convergence about the connection_rate

### ISSUE THREAD

**Issue by 1496nuonuo** [rruisong/pytorch_federated_learning#4]
I have done the experiment on the MINST. When connection_rate = 1, it is very easy to converge for about 400 rounds. On the contrary, I  test the connection_rate  = 0.5 and 0.2 and 0.1. It fails to converge. I don't know if someone has the same problem? 
![image](https://github.com/rruisong/pytorch_federated_learning/assets/91582947/83e96c75-765b-4b34-bfb8-2773518d9cf0)

**Comment by rruisong** [comment]
The customized connection ratios were previously unsupported. Can you try the new branch - "issue#4"? I have addressed this issue by implementing a recalibration of the total number of data points for all clients selected on the server.

**Comment by 1496nuonuo** [comment]
I have found a big bug in your code.‘fl_main’
```
for global_round in pbar:
        for client_id in trainset_config['users']:
            # Local training
            if config["client"]["fed_algo"] == 'FedAvg':
                client_dict[client_id].update(global_state_dict)
                state_dict, n_data, loss = client_dict[client_id].train()
                fed_server.rec(client_dict[client_id].name, state_dict, n_data, loss)
            elif config["client"]["fed_algo"] == 'SCAFFOLD':
                client_dict[client_id].update(global_state_dict, scv_state)
                state_dict, n_data, loss, delta_ccv_state = client_dict[client_id].train()
                fed_server.rec(client_dict[client_id].name, state_dict, n_data, loss, delta_ccv_state)
            elif config["client"]["fed_algo"] == 'FedProx':
                client_dict[client_id].update(global_state_dict)
                state_dict, n_data, loss = client_dict[client_id].train()
                fed_server.rec(client_dict[client_id].name, state_dict, n_data, loss)
            elif config["client"]["fed_algo"] == 'FedNova':
                client_dict[client_id].update(global_state_dict)
                state_dict, n_data, loss, coeff, norm_grad = client_dict[client_id].train()
                fed_server.rec(client_dict[client_id].name, state_dict, n_data, loss, coeff, norm_grad)

        # Global aggregation
        fed_server.select_clients()
```

I think the select should be ahead of the rec.
It should be changed to like this
```        
        fed_server.select_clients(float(config["system"]["connection_rate"])) # Cconnection_rate
        for client_id in fed_server.selected_clients:
```

**Comment by 1496nuonuo** [comment]
I change it then I have fix such problem. Plus, there is an erratum to the original paper.
![image](https://github.com/rruisong/pytorch_federated_learning/assets/91582947/616465a0-c889-413e-91bf-4c23c536c16d)
![image](https://github.com/rruisong/pytorch_federated_learning/assets/91582947/8e15dfea-ba68-42dc-ac9f-e90331bae57e)
Your former code is choose the summation of all K clients data number as dominator.

**Comment by rruisong** [comment]
It depends on the use cases. If the server requires an additional selection protocol post-receipt of data from clients, it's feasible to implement the selection process after the data has been received. 

For evaluative purposes, it might be more practical and generalizable to arrange client selection subsequently. As noted in the prior comment, I have addressed this issue by recalibrating the total data count on the server. I hope it can be helpful.

**Comment by 1496nuonuo** [comment]
OK, thank you. Your codes helps me a lot as a novice of Federated Learning O(∩_∩)O~

**Comment by rruisong** [comment]
I appreciate your issue report and I'm glad to know that the code can be useful for you! I am closing this issue.
