### ISSUE TITLE
The Hardware environment

### ISSUE THREAD

**Issue by simba-axin** [rruisong/pytorch_federated_learning#6]
Hello, could you please tell me what the minimum hardware requirements are for running this project? For example, memory size, video memory size, etc., because it crashed directly when I tried to run it on my 16g computer.

**Comment by rruisong** [comment]
The minimum requirements vary based on the chosen model and task. For example, training a simple model like LeNet on a basic dataset such as MNIST requires relatively modest computational resources. 

Maybe you can provide more information about your hardware and software specifications.
